### ISSUE TITLE
Error Copying the Template in Volume Using the nginx-ssl Container (README)

### ISSUE THREAD

**Issue by frostyandy2k** [ekkis/nginx-proxy-LE-docker-compose#2]
The nginx-ssl volume is read only in the docker-compose.yml

Executing
`docker cp nginx.tmpl nginx-ssl:/etc/docker-gen/templates/` results in a write error: 

`Error response from daemon: mounted volume is marked read-only`

It should probably get written with the help of the `nginx-gen` container (it has rw permissions):
`docker cp nginx.tmpl nginx-gen:/etc/docker-gen/templates/`

**Comment by ekkis** [comment]
@frostyandy2k: I'm sorry, my bad.  that should have read: to the nginx-gen container as you pointed out.  I've fixed it
