### ISSUE TITLE
ssl question

### ISSUE THREAD

**Issue by xgodon** [ekkis/nginx-proxy-LE-docker-compose#3]
I used your dockerfile but i can only connect via my containers via http. How can i set default to https?
the generated default.conf only listen 80 port.

**Comment by ekkis** [comment]
if the default.conf is only listening on port 80 it means that the certificates were not generated.  these get generated when you bring up a container with the right environment variables.  you need to set VIRTUAL_HOST, LETSENCRYPT_HOST and LETSENCRYPT_EMAIL.  read the docs elsewhere about that.  when a container comes up with these values set, it generates the certs and rebuilds the default.conf

**Comment by xgodon** [comment]
but i set these vars :/

**Comment by ekkis** [comment]
then you should have a look at the nginx-ssl log to figure out why it's failing to generate the certificates.  unless they exist, the default.conf will not listen on SSL

**Comment by xgodon** [comment]
i took exactly this docker compose so i don't see any reason of this happening, i have nothing in logs, even with debug mode activated. The directory of the domain certs is created, but it is empty :/

**Comment by ekkis** [comment]
having the docker-compose is no guarantee that the components will work.  there are environmental factors beyond the capability of the docker-compose.

as for the logs, they couldn't possibly be empty.  do `docker logs nginx-ssl`

**Comment by ekkis** [comment]
if you want to chat we can meet on freenode #docker

**Comment by xgodon** [comment]
ok so i spent all the morning on this issue, i managed to make it work but i didn't undertand how it works.

so i had no erros in logs :

`nginx-gen      | 2017/05/28 13:05:12 Received event start for container fa85a3bf7f3e
nginx-ssl      | 2017/05/28 13:05:12 Received event start for container fa85a3bf7f3e
nginx-gen      | 2017/05/28 13:05:17 Debounce minTimer fired
nginx-gen      | 2017/05/28 13:05:17 Generated '/etc/nginx/conf.d/default.conf' from 4 containers
nginx-gen      | 2017/05/28 13:05:17 Sending container 'nginx-proxy' signal '1'
nginx-ssl      | 2017/05/28 13:05:27 Debounce minTimer fired
nginx-ssl      | 2017/05/28 13:05:27 Generated '/app/letsencrypt_service_data' from 2 containers
nginx-ssl      | 2017/05/28 13:05:27 Running '/app/update_certs'
nginx-ssl      | Creating/renewal wiki.exemple.duckdns.org certificates... (wiki.exemple.duckdns.org)
nginx-ssl      | 2017-05-28 13:05:27,428:INFO:simp_le:1211: Generating new account key
nginx-ssl      | 2017-05-28 13:05:28,038:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
nginx-ssl      | 2017-05-28 13:05:28,936:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): letsencrypt.org
nginx-ssl      | 2017-05-28 13:05:30,404:INFO:requests.packages.urllib3.connectionpool:207: Starting new HTTP connection (1): wiki.exemple.duckdns.org
nginx-proxy    | wiki.exemple.duckdns.org 86.233.92.39 - - [28/May/2017:13:05:30 +0000] "GET /.well-known/acme-challenge/xxxxxxxxxxxxxxxxxxxx HTTP/1.1" 200 87 "-" "python-requests/2.8.1"
`

but the certs/wiki.exemple.duckdns.org was empty

i went into the nginx-ssl container and executed ./letsencrypt_service
then the certs were created.
if you have an explaination... i'd be glad to hear it.
i think i messed up somewhere...

i couldn't make it work with docker run either so i guess i'm doing something wrong.

**Comment by ekkis** [comment]
this kind of stuff is very environment dependent.  if you got it to work, good.  I think we can just leave it at that

**Comment by ekkis** [comment]
if you had figured out what the issue was e.g. perhaps a question of sequence or something misconfigured I would have been more than happy to document it
